---

# docker-compose up  -d     # Run in detached mode

version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
#    ports:
#      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    stdin_open: true

  mongo:
    container_name: mongodb
#    ports:
#      - "27017:27017"
    image: mongo:4.4.3
    restart: always
    volumes:
      - ./mongodb_data:/data/db
